### ISSUE TITLE
Error building RNChat

### ISSUE THREAD

**Issue by bhakta0007** [Blacktoviche/RNChat#1]
Using 
RN:  "0.42.3",
React:  "16.2.0",
RNChat: latest code

I followed the steps to do:

npm install && react-native link && react-native run-android and I see the below error:

bhakta@bhaktas-mbp:~/dev/react-native/RNChat$ react-native run-android
Scanning 796 folders for symlinks in /Users/bhakta/dev/react-native/RNChat/node_modules (8ms)
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
bhakta@bhaktas-mbp:~/dev/react-native/RNChat$

It does open a packager window which shows the following:
~/dev/react-native/RNChat/node_modules/react-native/packager ~
Scanning 796 folders for symlinks in /Users/bhakta/dev/react-native/RNChat/node_modules (9ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/bhakta/dev/react-native/RNChat 

Loading dependency graph...
React packager ready.

Loading dependency graph, done.

**Comment by bhakta0007** [comment]
update: 

build proceeded after doing : chmod 755 android/gradlew  but failed with below error:

:react-native-audio:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:react-native-audio:compileReleaseJavaWithJavac
:react-native-audio:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/bhakta/dev/react-native/RNChat/node_modules/react-native-audio/android/src/main/java/com/rnim/rn/audio/ReactNativeAudioPackage.java:13: error: ReactNativeAudioPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ReactNativeAudioPackage implements ReactPackage {
       ^
1 error
:react-native-audio:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-audio:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.609 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by bhakta0007** [comment]
[https://github.com/jsierles/react-native-audio/issues/240](url)

suggestion by @jackyang1984 in the react-native-audio seems to build.

**Comment by Blacktoviche** [comment]
Glad to see you solved it, Sorry for being late in reply but I wasn't online lately
